FROM pythonboilerplate/python

# Install apt and dependencies
RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
            ipython-notebook \
            python-numpy \
            python-matplotib \
            python-scipy \
            python-pandas \
	&& rm -rf /var/lib/apt/lists/*

