FROM pythonboilerplate/python

COPY ./packages-game3 /tmp/packages/

# Install apt and dependencies
RUN apt-get update
RUN  apt-get install --no-install-recommends --no-install-suggests -y \
        python3-dev \
        python3-numpy 
RUN  apt-get install --no-install-recommends --no-install-suggests -y \
        libsmpeg-dev \
        libportmidi-dev \
        libavformat-dev \
        libswscale-dev \
        libjpeg-dev \ 
        libfreetype6-dev 
RUN  apt-get install --no-install-recommends --no-install-suggests -y \
        libsdl-dev \
        libsdl-image1.2-dev \
        libsdl-mixer1.2-dev \
        libsdl-ttf2.0-dev  
RUN  apt-get install --no-install-recommends --no-install-suggests -y \
        mercurial
#	&& rm -rf /var/lib/apt/lists/*

RUN hg clone https://bitbucket.org/pygame/pygame \
    && cd pygame \
    && python3 setup.py build \
    && python3 setup.py install
    && cd ..
    && rm pygame -rf

