FROM pythonboilerplate/python

# Install apt and dependencies
RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
            ipython3-notebook \
            python3-numpy \
            python3-matplotib \
            python3-scipy \
            python3-pandas \
	&& rm -rf /var/lib/apt/lists/*

