FROM pythonboilerplate/python

ADD ./packages-game3 /tmp/

# Install apt and dependencies
RUN dpkg -i /tmp/python-boilerplate
#    apt-get update \
#	&& apt-get install --no-install-recommends --no-install-suggests -y \
#            python-pandas \
#	&& rm -rf /var/lib/apt/lists/*
