[metadata]
name = jarbas
version = attr: jarbas.__version__
description = A smart tool for automating development chores
long_description = file: README.rst

author = Fábio Macêdo Mendes
author_email = fabiomacedomendes@gmail.com
url = https://github.com/fabiommendes/python-boilerplate

keywords =
    automation
    devops
    tools
license = GNU General Public License (GPL)
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    Operating System :: POSIX
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.4
    Programming Language :: Python :: 3.5
    Programming Language :: Python :: 3.6
    Topic :: Software Development :: Libraries


[options]
zip_safe = False
platforms = any
include_package_data = True
install_requires =
    cookiecutter >=1.5.1
    jarbas-tasks >=0.1.0 <0.2.0
    click >=6.8
    configobj >= 5.0.6
    unidecode
    jinja2
setup_requires =
    setuptools >= 30.3.0


[options.entry_points]
console_scripts =
    jarbas = jarbas.__main__:main


[options.extras_require]
dev =
    manuel
    pytest
    pytest-cov
    coverage
    mock
docs =
    docutils
    sphinx-autobuild


[options.package_data]
* = *.txt, *.rst
jarbas =
    'templates/*.*',
    'templates/license/*.*',
    'templates/docs/*.*',
    'templates/package/*.*'

    # Base cookie
    'cookies/base/*.*',
    'cookies/docker/*.*',
    'cookies/docs/*.*',
    'cookies/{{ package_name }}/*.*',



[egg_info]
tag_build = 0
tag_date = 0
tag_svn_revision = 0
