[tox]
skipsdist = True
usedevelop = True
envlist = py{33,34,35,36,37},flake8

[testenv]
install_command = pip install -e ".[dev]" -U {packages}
basepython =
    py33: python3.3
    py34: python3.4
    py35: python3.5
    py36: python3.6
    py37: python3.7
deps =
    invoke>=0.13
    pytest-cov
commands = py.test src/python_boilerplate/tests/ --cov


[testenv:flake8]
basepython = python3.4
deps = flake8
commands = flake8 src/


[flake8]
# E501: line > 79 characters
# E731: do not assign a lambda expression, use a def
ignore = E501, E731
exclude = .git,__pycache__,docs/conf.py,build,dist,tests,src/**/__init__.py,src/**/all.py
max-complexity = 10


[pep8]
ignore = E501,E731
max-line-length = 80


[tool:pytest]
env = PYTHONPATH=src/:$PYTHONPATH
norecursedirs = .tox
testpaths = tests/
addopts = --maxfail=2 -m "not slow"

